CREATE TABLE EmployeeBasicInfo(
	EmployeeId nvarchar(50) NOT NULL,
	FirstName nvarchar(50) NOT NULL,
	LastName nvarchar(50) NULL,
	DisplayName nvarchar(50) NULL,
	MiddleName nvarchar(50) NULL,
	Suffix nvarchar(5) NULL,
	TimeZone char(10) NULL,
	CountryCode nvarchar(5) NULL,
	AreaCode nvarchar(5) NULL,
	LocalNumber nvarchar(50) NULL,
	Extension nvarchar(10) NULL,
	PrimaryMail nvarchar(50) NULL,
	SecondaryMail nvarchar(50) NULL,
	TertiaryMail nvarchar(50) NULL,
	ADSUserID nvarchar(25) NULL,
	ADSAccountCreatedDate datetime NULL,
	ModifiedBy bigint NOT NULL,
	ModifiedOn datetime NOT NULL,
	MobileNumber nvarchar(50) NULL,
	HomePhoneNo nvarchar(50) NULL,
	EmployeeStatus nvarchar(25) NULL,
	EffectiveDate datetime NULL,
	Photo nvarchar(500) NULL,
	PhotoContent image NULL,
	IsStorage bit NULL,
	FTPFileName nvarchar(500) NULL,
	StorageUpdateOn datetime NULL
);