CREATE TABLE EmployeeBasicInfo(
	EmployeeId varchar(50) NOT NULL,
	FirstName varchar(50) NOT NULL,
	LastName varchar(50) NULL,
	DisplayName varchar(50) NULL,
	MiddleName varchar(50) NULL,
	Suffix varchar(5) NULL,
	TimeZone char(10) NULL,
	CountryCode varchar(5) NULL,
	AreaCode varchar(5) NULL,
	LocalNumber varchar(50) NULL,
	Extension varchar(10) NULL,
	PrimaryMail varchar(50) NULL,
	SecondaryMail varchar(50) NULL,
	TertiaryMail varchar(50) NULL,
	ADSUserID varchar(25) NULL,
	ADSAccountCreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
	ModifiedBy int NOT NULL,
	ModifiedOn TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);